---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library("tidyverse")
library("here")
library("janitor")
library("skimr")
library("naniar")

```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate<-read_csv(here("data", "heartrate.csv")) %>% janitor::clean_names()
```
```{r}
heartrate_long <- heartrate %>% 
pivot_longer(-patient, #patient will not pivot
             names_to = "drug", #want column names to be moved to a new column
             values_to = "heartrate" # values moved to
             )
heartrate_long
```
```{r}
heartrate_long %>% 
  filter(drug == "a") %>% 
  ggplot(aes(x=patient, y=heartrate, fill = patient))+
  geom_col()+
  labs(title = "Comparison of Patient Heartrates for Drug A", 
       x = "Patient", #can type NULL if you don't want a label here to clean it up
       y = "Heartrate")
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate_long %>% 
  ggplot(aes(x=drug, y=heartrate, fill = drug))+
  geom_boxplot(alpha = 0.7)+ #adjust the transparency of the plots
  labs(title = "Comparison of Heartrate Drugs", 
       x = "Drug", 
       y = "Heartrate")
```

